// Turns design/tokens/*.json (W3C Design Tokens format) into dist/tokens.css and enforces the contrast floor.
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import { contrast, inGamut } from "./color.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
export const FLOORS = { text: 4.5, graphic: 3 };

const isToken = (node) => node && typeof node === "object" && "$value" in node;

/** Flattens a token tree into [path, token] pairs, skipping `$`-prefixed metadata keys. */
function flatten(tree, path = []) {
  return Object.entries(tree)
    .filter(([key]) => !key.startsWith("$"))
    .flatMap(([key, node]) => (isToken(node) ? [[[...path, key], node]] : flatten(node, [...path, key])));
}

const varName = (path) => `--ma-${path.join("-")}`;

function cssValue(token) {
  const value = token.$value;
  if (typeof value === "string") {
    const ref = /^\{([^}]+)\}$/.exec(value);
    return ref ? `var(${varName(ref[1].split("."))})` : value;
  }
  if (token.$type === "fontFamily") return value.map((f) => (/\s/.test(f) ? `"${f}"` : f)).join(", ");
  if (token.$type === "cubicBezier") return `cubic-bezier(${value.join(", ")})`;
  return String(value);
}

/** Reads every token file of a directory: `base.json` plus one file per direction. */
export function readTokens(dir) {
  const files = readdirSync(dir).filter((f) => f.endsWith(".json")).sort();
  const base = JSON.parse(readFileSync(join(dir, "base.json"), "utf8"));
  const directions = Object.fromEntries(
    files
      .filter((f) => f !== "base.json")
      .map((f) => [f.replace(/\.json$/, ""), JSON.parse(readFileSync(join(dir, f), "utf8"))]),
  );
  return { base, directions };
}

/** Colour tokens of a direction, per theme: [{name, role, light, dark}]. */
export function colours(direction) {
  return flatten(direction.color ?? {}).map(([path, token]) => ({
    name: path.join("-"),
    role: token.$extensions?.mandato?.role,
    light: token.$value,
    dark: token.$extensions?.mandato?.dark,
  }));
}

/** Every pair the floor applies to: each text and graphic colour against each surface, per theme. */
export function pairs(direction) {
  const all = colours(direction);
  const surfaces = all.filter((c) => c.role === "surface");
  return ["light", "dark"].flatMap((theme) =>
    all
      .filter((c) => c.role in FLOORS)
      .flatMap((fg) =>
        surfaces.map((bg) => ({
          theme,
          fg: fg.name,
          bg: bg.name,
          min: FLOORS[fg.role],
          ratio: contrast(fg[theme], bg[theme]),
        })),
      ),
  );
}

export function buildTokens(dir) {
  const { base, directions } = readTokens(dir);
  const errors = [];
  const declarations = (entries) => entries.map(([name, value]) => `  ${name}: ${value};`).join("\n");

  const blocks = [`:root {\n${declarations(flatten(base).map(([p, t]) => [varName(p), cssValue(t)]))}\n}`];
  for (const [name, direction] of Object.entries(directions)) {
    const nonColour = flatten(direction).filter(([path]) => path[0] !== "color");
    const cols = colours(direction);
    for (const c of cols) {
      for (const theme of ["light", "dark"]) {
        if (!c[theme]) errors.push(`${name} ${theme} ${c.name}: missing value`);
        else if (!inGamut(c[theme])) errors.push(`${name} ${theme} ${c.name}: ${c[theme]} is outside sRGB`);
      }
      if (!["surface", "text", "graphic", "decor"].includes(c.role)) errors.push(`${name} ${c.name}: unknown role ${c.role}`);
    }
    if (errors.length) continue;
    for (const p of pairs(direction)) {
      if (p.ratio < p.min)
        errors.push(`${name} ${p.theme} ${p.fg} on ${p.bg}: ${p.ratio.toFixed(2)}:1 is below ${p.min}:1`);
    }
    const light = [...nonColour.map(([p, t]) => [varName(p), cssValue(t)]), ...cols.map((c) => [varName(["color", c.name]), c.light])];
    const dark = cols.map((c) => [varName(["color", c.name]), c.dark]);
    const sel = `[data-direction="${name}"]`;
    blocks.push(`/* ${name} light */\n${sel} {\n  color-scheme: light;\n${declarations(light)}\n}`);
    blocks.push(
      `/* ${name} dark */\n@media (prefers-color-scheme: dark) {\n  ${sel}:not([data-theme="light"]) {\n    color-scheme: dark;\n${declarations(dark).replace(/^/gm, "  ")}\n  }\n}\n${sel}[data-theme="dark"] {\n  color-scheme: dark;\n${declarations(dark)}\n}`,
    );
  }
  return { css: `/* Generated by scripts/build-tokens.mjs from tokens/*.json. Do not edit. */\n\n${blocks.join("\n\n")}\n`, errors };
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  const dir = resolve(process.argv[2] ?? join(HERE, "..", "tokens"));
  const out = resolve(process.argv[3] ?? join(HERE, "..", "dist", "tokens.css"));
  const { css, errors } = buildTokens(dir);
  if (errors.length) {
    for (const e of errors) console.error(e);
    process.exit(1);
  }
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, css);
  console.log(`wrote ${out}`);
}
